wipbase:
  build: .
  ports:
   - "9000:9000"
  links:
   - db
   - mq
db:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: whipper_base
mq:
  image: tutum/rabbitmq
  environment:
   RABBITMQ_PASS: 654321